apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: business-manager
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: business-manager-prd
          image: ghcr.io/niridoy/sample-php:main
          env:
            - name: ENV
              value: "prd"
