apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: business-manager-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/niridoy/k8s-gitops.git
    targetRevision: main
    path: business-manager/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: business-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
