apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/niridoy/k8s-gitops.git
    targetRevision: main
    path: product-service/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
