apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: hotel-app
spec:
  template:
    spec:
      containers:
        - name: sample-php-dev
          image: ghcr.io/niridoy/node-web-app:70f96abebf8f3b9ca13304e97e0d6b0dd5b5bb20
          env:
            - name: ENV
              value: "dev"
