apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
        - name: sample-php-app
          image: ghcr.io/niridoy/sample-php-app:dev
          env:
            - name: ENV
              value: "dev"
