apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: hotel-app
spec:
  template:
    spec:
      containers:
        - name: sample-php-stg
          image: ghcr.io/niridoy/sample-php:main
          env:
            - name: ENV
              value: "stg"
