apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: hotel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: sample-php-app
          image: ghcr.io/niridoy/sample-php-app:450b84a7355efccefd313b2a97381be164906cf3
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent # <-- Only pull if not local
          ports:
            - containerPort: 80
