apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: user-service
          image: ghcr.io/niridoy/rocket-user-service:dev-main-37
          env:
            - name: ENV
              value: "dev"
