apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service

spec:
  template:
    spec:
      containers:
        - name: user-service-dev
          image: ghcr.io/niridoy/rocket-user-service:dev-main-37
