apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: user-service
          image: ghcr.io/my-org/user-service:latest
          env:
            - name: ENV
              value: "prd"
