apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: business-manager
spec:
  template:
    spec:
      containers:
        - name: business-manager-dev
          image: ghcr.io/niridoy/sample-php:dev-main-29
          env:
            - name: ENV
              value: "dev"
